### ISSUE TITLE
dynamodb_20120810.nim(4341, 10) Error: use ssl

### ISSUE THREAD

**Issue by mrichman** [disruptek/atoz#17]
I get this error when I compile. Using `atoz-2626.5.2` with Nim 2.0.8 installed via Homebrew on macOS 14.6:

`/Users/mrkrchm/.nimble/pkgs2/atoz-2626.5.2-42fd535221574157cd17052485cc74eea724d5de/atoz/dynamodb_20120810.nim(4341, 10) Error: use ssl`

```nim
import awslambda, json
import asyncdispatch
import atoz/dynamodb_20120810

proc handler(event: JsonNode, context: LambdaContext): JsonNode =
  let
    body: JsonNode = %* {"TableName": "my-table"}
    header: JsonNode = newJObject()
    request = describeTable.call(nil, nil, header, nil, body)
    response = waitfor request.issueRequest()

when isMainModule:
  startLambda(handler)
```
Also, are there any examples beyond the one SQS example in the README?

**Comment by disruptek** [comment]
Add `--define:ssl` to a `nim.cfg` or pass it on the command-line.

**Comment by mrichman** [comment]
Thanks that worked. Added `define:ssl` to a new `nim.cfg`.

What about examples?

**Comment by disruptek** [comment]
Here's an example I found using GitHub's search feature:

https://github.com/epiphone/serverless-nim-sample
