### ISSUE TITLE
Error: ambiguous call

### ISSUE THREAD

**Issue by mrichman** [disruptek/atoz#18]
Following this [example](https://github.com/epiphone/serverless-nim-sample/blob/master/src/createUrl.nim#L23) I get the following compiler error:

Error: ambiguous call; both dynamodb_20120810.call(call_553652223: Call_Query_553652209, path: JsonNode, query: JsonNode, header: JsonNode, formData: JsonNode, body: JsonNode, content: string) [proc declared in /Users/mrkrchm/.nimble/pkgs2/atoz-2626.5.2-42fd535221574157cd17052485cc74eea724d5de/atoz/dynamodb_20120810.nim(2718, 6)] and dynamodb_20120810.call(call_553652224: Call_Query_553652209, body: JsonNode, ExclusiveStartKey: string, Limit: string) [proc declared in /Users/mrkrchm/.nimble/pkgs2/atoz-2626.5.2-42fd535221574157cd17052485cc74eea724d5de/atoz/dynamodb_20120810.nim(2732, 6)] match for: (Call_Query_553652209, JsonNode)

**Comment by disruptek** [comment]
Disambiguate the call using one of the function arguments which doesn't occur in the other signature; this is standard behavior for Nim...
